# -*- coding: utf-8 -*-
"""BTL_KPDL_NHOM..ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1CWb9KujLlnk47A5P2o_zN55OSKyePbv2

**3. TIỀN XỬ LÝ DỮ LIỆU**
"""

#Khai báo thư viện cần dùng
import pandas as pd
import numpy as np
import seaborn as sns
from sklearn.preprocessing import MinMaxScaler, RobustScaler, StandardScaler
from sklearn.preprocessing import LabelEncoder, OneHotEncoder, OrdinalEncoder

# đọc dữ liệu
df = pd.read_csv("Healthcare.csv")
# in ra kich thuoc du lieu
df.shape

df.describe()

df.info()

"""***3.1. Làm sạch dữ liệu***"""

# kiểm tra dữ liệu bị khuyết
df.isna()

df.isna().sum()

# Kiểm tra trùng lặp
df.duplicated().sum()

#Kiểm tra dữ liệu outliners bằng cách vẽ boxplot cho từng thuộc tính
#Vẽ boxplot của 4 cột số
import matplotlib.pyplot as plt # Import matplotlib

# Chọn 4 cột số để vẽ boxplot
selected_numerical_cols = ['Patient_ID', 'Age', 'Symptom_Count', 'Gender']

fig, axes = plt.subplots(2, 2, figsize=(10, 8)) # 2 hàng, 2 cột cho 4 boxplot
axes = axes.flatten()

#Tiêu đề cho mô hình
fig.suptitle("Boxplot cho các thuộc tính số được chọn", fontsize=16)

for index, col in enumerate(selected_numerical_cols):
    #Hiển thị tiêu đề cho từng ô con
    axes[index].set_title("Boxplot của {}".format(col))
    #ve boxplot cho từng ô con
    sns.boxplot(y=df[col], ax=axes[index])

plt.tight_layout()
#Tạo khoảng cách giữa các ô con
plt.subplots_adjust(hspace=0.3, wspace=0.4)
plt.show()

"""**3.2. Chuẩn hóa/biến đổi dữ liệu và  Rút gọn dữ liệu**


"""

df = df.drop('Patient_ID',axis=1)

# các giá trị ở Symptoms
df['Symptoms'].unique()

df['Disease'].unique()

"""One-Hot Encoding: tách thuộc tính thành các cột 0/1 để tránh thứ tự giả."""

# 1. Tách chuỗi triệu chứng thành danh sách các triệu chứng
df["Symptoms_list"] = df["Symptoms"].str.split(",").apply(lambda x: [i.strip() for i in x])

# 2. "Phát nổ" (explode) DataFrame để mỗi triệu chứng trở thành một hàng riêng biệt
df_exploded = df.explode("Symptoms_list")

# 3. Áp dụng One-Hot Encoding cho các triệu chứng đã được "phát nổ"
dummy = pd.get_dummies(df_exploded["Symptoms_list"])

# 4. Gom nhóm lại theo chỉ mục gốc (sử dụng max để lấy 0/1)
dummy_grouped = dummy.groupby(level=0).max()

# 5. Chuyển đổi sang kiểu số nguyên
dummy_grouped = dummy_grouped.astype(int)
# Final DF loại bỏ 2 cột "Symptoms" & without "Symptoms_list"
df = pd.concat([df.drop(columns=["Symptoms", "Symptoms_list"]), dummy_grouped], axis=1)

df['Gender'] = df['Gender'].apply(lambda x:1 if x == 'Male' else 0)

"""Label Encoding: biến mỗi nhãn thành số nguyên.

"""

disease_to_superclass = {
    # 1) Respiratory & Infections
    "COVID-19": "Respiratory/Infectious",
    "Asthma": "Respiratory/Infectious",
    "Bronchitis": "Respiratory/Infectious",
    "Pneumonia": "Respiratory/Infectious",
    "Tuberculosis": "Respiratory/Infectious",
    "Common Cold": "Respiratory/Infectious",
    "Sinusitis": "Respiratory/Infectious",
    "Influenza": "Respiratory/Infectious",

    # 2) Cardio-metabolic & Blood
    "Heart Disease": "Cardio-metabolic/Blood",
    "Hypertension": "Cardio-metabolic/Blood",
    "Diabetes": "Cardio-metabolic/Blood",
    "Thyroid Disorder": "Cardio-metabolic/Blood",
    "Obesity": "Cardio-metabolic/Blood",
    "Anemia": "Cardio-metabolic/Blood",

    # 3) Digestive & Liver
    "Gastritis": "Digestive/Liver",
    "IBS": "Digestive/Liver",
    "Ulcer": "Digestive/Liver",
    "Food Poisoning": "Digestive/Liver",
    "Liver Disease": "Digestive/Liver",

    # 4) Neurological & Stroke
    "Epilepsy": "Neuro/Stroke",
    "Migraine": "Neuro/Stroke",
    "Dementia": "Neuro/Stroke",
    "Parkinson's": "Neuro/Stroke",
    "Stroke": "Neuro/Stroke",

    # 5) Mental Health
    "Depression": "Mental Health",
    "Anxiety": "Mental Health",

    # 6) Immune / Allergy / Skin
    "Allergy": "Immune/Allergy/Skin",
    "Dermatitis": "Immune/Allergy/Skin",

    # 7) Other Chronic (Kidney, Joint)
    "Chronic Kidney Disease": "Other Chronic",
    "Arthritis": "Other Chronic",
}

df['Superclass'] = df['Disease'].map(disease_to_superclass)

df['Disease'].value_counts()

df['Superclass'].value_counts()

# mã hóa cột Country với Label encoder sử dụng scikit learn encoder = LabelEncoder()
le_disease = LabelEncoder()
df["Disease"] = le_disease.fit_transform(df["Disease"])

print("Disease classes (27 labels):")
print(le_disease.classes_)


le_super = LabelEncoder()
df["Superclass"] = le_super.fit_transform(df["Superclass"])

print("\nSuperclass classes (7 labels):")
print(le_super.classes_)

df

"""**3.4 Chia dữ liệu thành tập huấn luyện và tập kiểm tra (train/test).**"""

import numpy as np
import pandas as pd
from sentence_transformers import SentenceTransformer
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, LabelEncoder
import os # Import os for os.path.join

# Tải lại dữ liệu gốc để lấy văn bản 'Symptoms', vì nó đã bị loại bỏ khỏi 'df'
original_data = pd.read_csv('Healthcare.csv')

# Mục tiêu đã được mã hóa nhãn dưới dạng số nguyên trong df["Superclass"]
y = df["Superclass"]
# y_enc chính là y, vì nó đã được mã hóa
y_enc = y


X = pd.DataFrame()
X["Symptoms"] = original_data["Symptoms"]
X["Age"] = df["Age"]
X["Gender"] = df["Gender"]
X["Symptom_Count"] = df["Symptom_Count"]

# Chuyển đổi cột 'Gender' sang dạng số trong X
X['Gender'] = X['Gender'].apply(lambda x: 1 if x == 'Male' else (0 if x == 'Female' else 0)) # Assuming 'Other' also maps to 0

# Chia tập huấn luyện và kiểm tra
X_train, X_test, y_train, y_test = train_test_split(
    X, y_enc,
    test_size=0.2,
    random_state=42,
    stratify=y_enc
)

# Tải bộ mã hóa BERT/MiniLM
bert_model = SentenceTransformer("all-MiniLM-L6-v2")

# Mã hóa văn bản triệu chứng → nhúng dày đặc
train_symptoms = X_train["Symptoms"].astype(str).tolist()
test_symptoms  = X_test["Symptoms"].astype(str).tolist()

emb_train = bert_model.encode(train_symptoms, batch_size=64, show_progress_bar=True)
emb_test  = bert_model.encode(test_symptoms, batch_size=64, show_progress_bar=True)

print("Kích thước nhúng:", emb_train.shape)

# Các đặc trưng số: Age, Gender, Symptom_Count
num_cols = ["Age", "Gender", "Symptom_Count"]

scaler = StandardScaler()
num_train = scaler.fit_transform(X_train[num_cols])
num_test  = scaler.transform(X_test[num_cols])

# Nối [nhúng BERT | các đặc trưng số]
X_train_bert = np.hstack([emb_train, num_train])
X_test_bert  = np.hstack([emb_test, num_test])

print("Kích thước tập huấn luyện cuối cùng:", X_train_bert.shape)
print("Kích thước tập kiểm tra cuối cùng:", X_test_bert.shape)

from catboost import CatBoostClassifier
from sklearn.metrics import classification_report

cat = CatBoostClassifier(
    iterations=800,
    depth=8,
    learning_rate=0.03,
    loss_function="MultiClass",
    eval_metric="Accuracy",
    random_seed=42,
    verbose=100
)

cat.fit(X_train_bert, y_train)

# Dự đoán
y_pred = cat.predict(X_test_bert).flatten()

# Dự đoán
y_pred = cat.predict(X_test_bert).flatten()

# Tạo lại LabelEncoder cho các siêu lớp để đảm bảo tên mục tiêu chính xác
# Điều này là cần thiết vì 'le_super' có thể đã bị mất hoặc được tái huấn luyện trên dữ liệu số
# Chúng ta lấy trực tiếp các tên chuỗi duy nhất từ các giá trị của từ điển 'disease_to_superclass'
all_superclass_names = list(set(disease_to_superclass.values()))
# Tạo một LabelEncoder tạm thời và huấn luyện nó trên các tên chuỗi này
temp_le_super = LabelEncoder()
temp_le_super.fit(all_superclass_names)

print("=========== Báo cáo phân loại BERT + CatBoost (7 Siêu danh mục) ===========\n")
print(classification_report(
    y_test,
    y_pred,
    target_names=temp_le_super.classes_   # Sử dụng các lớp từ LabelEncoder được tạo lại
))